# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the PECI core drivers.
#

# Core functionality
obj-$(CONFIG_PECI_LEGACY)		+= peci-core.o
obj-$(CONFIG_PECI_CHARDEV_LEGACY)	+= peci-dev.o

# Hardware specific bus drivers
obj-y				+= busses/
